### PR TITLE
Create User-Friendly Error Popups

### PR DESCRIPTION
**Pull request by chef-louis**
#167

### CODE REVIEW

**Review by qisforq — COMMENTED** [review]
The new error messages look great!

However I noticed that the Season Highlights component does not seem to be exiting the loading animation.

I tried these URLs:

- http://localhost:3000/dashboard/vsa-23/199
- http://localhost:3000/dashboard/vsa-23/200
- http://localhost:3000/dashboard/vsa-23/202

However, when I check the same URLs on the `dev` branch, Season Highlights loads fine. 

Here's a screenshot of what I see for these URLs:
Screenshot 2024-04-04 at 7 36 35 PM

**Comment by chef-louis** [comment]
@qisforq Good catch and thanks for flagging with such detail. I've pushed up a fix for the season highlights component. Let me know if that looks better for you.

We can also talk separately about whether we like the design of these messages or not. I've kept it possibly too simple but would be good to get the thoughts from the group as well.

**Comment by qisforq** [comment]
Hey @chef-louis just noticed you closed this without merging. Are you planning on adding this into a new PR?

**Comment by chef-louis** [comment]
Yah I’m going to add a new PR with the updated changes we discussed. Won’t
get to it until later tonight so wanted to pull the PR in the meantime.

**Pull request closed without merging**
