### PR TITLE
UI dashboard adjustments

### PR DESCRIPTION
**Pull request by pm-moyanor**
- Alignment and margins in all components
- replace font var with next/font
- Latest match : overflow scroll on descriptions 
- Profile: overflow Bio
- Season layout: adjust margins, reduce height in "empty data"
- past matches: alignment and adjust responsive feature
- popup card: alignment and simple animation
- teammates: styling, 1 column/rox (scroll x and y)

no animations

### CODE REVIEW

**Comment by chef-louis** [comment]
@pm-moyanor I really the look & feel of the improvements as a whole.

Just one area that looks a bit odd to me is in the "LatestMatch" component, the latest ratings look a bit crammed on the right and left margins (screenshot below). It feels a bit uneven compared to the other rating containers.

Screenshot from 2024-04-10 12-44-07

**Comment by pm-moyanor** [comment]
oh yes, I see it, I'll fix it later today. thanks for the feedback :)

**Comment by pm-moyanor** [comment]
I fixed the margins on the latest match card, let me know if you see something else. I think the last section (past matches and teammates) looks unbalanced and need more work, to render in even heights. Will work on it with the animations

**Comment by chef-louis** [comment]
Looks great!

**Pull request merged**
