### PR TITLE
Add Privacy Policy and Terms of Use pages

### PR DESCRIPTION
**Pull request by qisforq**
#36

### CODE REVIEW

**Comment by qisforq** [comment]
@chef-louis I added the links to the Privacy Policy and Terms of Use for sign-up page in this PR

**Review by chef-louis — APPROVED** [review]
@qisforq I've updated the default styling of the links on the sign-up page to make it clear the "Terms" and "Privacy Policy" are clickable items. Also I've updated the default to open the respective pages into it's a new tab so the user doesn't lose their progress on the sign-up.

**Comment by qisforq** [comment]
> @qisforq I've updated the default styling of the links on the sign-up page to make it clear the "Terms" and "Privacy Policy" are clickable items. Also I've updated the default to open the respective pages into it's a new tab so the user doesn't lose their progress on the sign-up.
> 
> Otherwise, I like the footer changes and the pages themselves. Thanks for the update

I saw those changes, that was good thinking. This was very timely since a privacy policy is necessary if we are using google analytics

**Comment by chef-louis** [comment]
Nice. I didn't know that -- good timing for sure.

**Pull request merged**
