### PR TITLE
Api refactor

### PR DESCRIPTION
**Pull request by chef-louis**
#135, #159, #161, #162 

Tagged team this with Hector and think we have a good working solution for the unified API endpoint for the dashboard data.

Once the PR is merged, we will deprecate the old lambda functions and API end points in the API Gateway.

### CODE REVIEW

**Comment by qisforq** [comment]
Really nice job overall @HectorAgudelo @chef-louis. I added a couple comments about typescript-related warnings I received, if you could check those out before we merge this

**Comment by chef-louis** [comment]
Taking a look

**Comment by chef-louis** [comment]
@qisforq Updated. Let me know if there are any others I missed.

**Review by qisforq — APPROVED** [review]
Everything looks good! Nice work again @HectorAgudelo and @chef-louis

**Pull request merged**
