### PR TITLE
feat: add Top Action Reels thumbnail component

### PR DESCRIPTION
**Pull request by chef-louis**
#251

### CODE REVIEW

**Review by qisforq — APPROVED** [review]
Finally got a chance to review, the new thumbnail looks good, I just noticed the colors are not split diagonally, but vertically. Is that the correct behavior?
Screenshot 2024-05-11 at 5 53 46 PM

I'm approving anyway because that's just a minor cosmetic thing

**Comment by chef-louis** [comment]
Hmm yah that's really strange... it didn't look like that before but I definitely see it now as well. I'll get it fixed and update this PR.

**Comment by chef-louis** [comment]
@qisforq check one more time -- I hardcoded the rotation variable in the tailwind styling and the diagonal is showing up again for me. Let me know if that's not the case for you and I'll keep digging to figure out what's going on.

**Comment by qisforq** [comment]
@chef-louis sorry for the delay responding. The diagonal is showing up for me now! Thanks for fixing that

**Pull request merged**
